# Generated by Django 5.1.4 on 2024-12-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='TaskList',
            new_name='tasklist',
        ),
    ]
