# Generated by Django 5.2 on 2025-08-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_alter_task_task_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='password', max_length=25),
            preserve_default=False,
        ),
    ]
