# Generated by Django 5.1.4 on 2024-12-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('TaskList', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_desc', models.CharField(max_length=100)),
                ('task_type', models.CharField(max_length=50)),
                ('task_due', models.DateField()),
                ('task_weight', models.IntegerField()),
                ('accname', models.CharField(max_length=50)),
            ],
        ),
    ]
